{
  parserClass="com.github.alexeybuzdin.uxmarkup.parser.UxParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Ux"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.alexeybuzdin.uxmarkup.psi"
  psiImplPackage="com.github.alexeybuzdin.uxmarkup.psi.impl"

  elementTypeHolderClass="com.github.alexeybuzdin.uxmarkup.psi.UxTypes"
  elementTypeClass="com.github.alexeybuzdin.uxmarkup.psi.UxElementType"
  tokenTypeClass="com.github.alexeybuzdin.uxmarkup.psi.UxTokenType"

  psiImplUtilClass="com.github.alexeybuzdin.uxmarkup.psi.impl.UxPsiImplUtil"
}

uxFile ::= node?

tag_start ::= '<'
tag_end   ::= '>'
slash     ::= '/'
equals    ::= '='
colon     ::= ':'
sign      ::= equals | colon

comment_start ::= '<!--'
comment_end ::= '-->'

node ::= comment*(node_empty | node_inner)
node_empty ::= tag_start node_name (attribute)* slash tag_end
node_inner ::= tag_start node_name (attribute)* tag_end node_body tag_start slash node_name tag_end

node_body ::= node*
node_name ::= IDENTIFIER

attribute ::= attribute_name equals STRING
attribute_name ::= attribute_schema? IDENTIFIER
attribute_schema ::= IDENTIFIER colon

comment ::= comment_start '.'* comment_end


