{
  parserClass="com.github.alexeybuzdin.uxmarkup.parser.UxParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Ux"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.alexeybuzdin.uxmarkup.psi"
  psiImplPackage="com.github.alexeybuzdin.uxmarkup.psi.impl"

  elementTypeHolderClass="com.github.alexeybuzdin.uxmarkup.psi.UxTypes"
  elementTypeClass="com.github.alexeybuzdin.uxmarkup.psi.UxElementType"
  tokenTypeClass="com.github.alexeybuzdin.uxmarkup.psi.UxTokenType"

  psiImplUtilClass="com.github.alexeybuzdin.uxmarkup.psi.impl.UxPsiImplUtil"
}

uxFile ::= node?

tag_start ::= '<'
tag_end   ::= '>'
slash     ::= '/'

comment_start ::= '<!--'
comment_end ::= '-->'

node ::= comment*(node_empty | node_inner)
node_empty ::= tag_start node_name  slash tag_end
node_inner ::= tag_start node_name tag_end node_body tag_start slash node_name tag_end

node_body ::= node*
node_name ::= IDENTIFIER

comment ::= comment_start '.'* comment_end


