{
  parserClass="com.github.alexeybuzdin.uxmarkup.parser.UxParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Ux"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.alexeybuzdin.uxmarkup.psi"
  psiImplPackage="com.github.alexeybuzdin.uxmarkup.psi.impl"

  elementTypeHolderClass="com.github.alexeybuzdin.uxmarkup.psi.UxTypes"
  elementTypeClass="com.github.alexeybuzdin.uxmarkup.psi.UxElementType"
  tokenTypeClass="com.github.alexeybuzdin.uxmarkup.psi.UxTokenType"

  psiImplUtilClass="com.github.alexeybuzdin.uxmarkup.psi.impl.UxPsiImplUtil"

  tokens = [
    JS_BODY="regexp:(.|\n)*"
  ]
}

uxFile ::= node?

tag_start ::= '<'
tag_end   ::= '>'
slash     ::= '/'
equals    ::= '='
colon     ::= ':'
sign      ::= equals | colon

private comment ::= (BLOCK_COMMENT)

js_start ::= "<JavaScript>"
js_end ::= "</JavaScript>"

node ::= comment*(node_empty | node_inner | js_node)
node_empty ::= tag_start NODE_NAME (attribute)* slash tag_end
node_inner ::= tag_start NODE_NAME (attribute)* tag_end node_body tag_start slash NODE_NAME tag_end

node_body ::= node*

attribute ::= (ATTRIBUTE_SCHEMA colon)? ATTRIBUTE_NAME equals STRING

js_node ::= js_start JS_BODY js_end